doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AppBundleDatabase:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Database/Entity'
                prefix: 'App\Domain\Database\Entity'
                alias: App
            AppBundleSequence:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Sequence/Entity'
                prefix: 'App\Domain\Sequence\Entity'
                alias: App