language: php
sudo: required
dist: trusty

php:
  - '7.2'

services:
  - mysql

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Run before the build
before_script:
  - mkdir -p build/logs # Create a folder to store clover files

install:
  - composer self-update
  - composer install --no-interaction --no-suggest

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml

# After success, run sh to bind coveralls
after_success:
  - export CODECOV_TOKEN="e51d30d0-d506-4d7e-8f61-4a0f9ee5ad78"
  - bash <(curl -s https://codecov.io/bash)
