language: php
sudo: required
dist: trusty

php:
  - '7.1.16'

services:
  - mysql

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Run before the build
before_script:
  - mkdir -p build/logs # Create a folder to store clover files

script:
  - composer self-update
  - composer install --no-interaction --no-suggest
  - composer require php-coveralls/php-coveralls:~1.0@stable # Require phpCoveralls
  - bin/console server:run &
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --test-suffix .php --colors

# After success, run sh to bind coveralls
after_success:
  - sh -c 'if( [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ); then php vendor/bin/coveralls -v; fi;'