language: php
sudo: required
dist: trusty

php:
  - '7.1.16'

services:
  - mysql

script:
  - composer self-update
  - composer install --no-interaction --no-suggest
  - bin/console server:run &
  - vendor/bin/phpunit