imports:
    - { resource: parameters.yml }
    - { resource: inc/chemical.yml }
    - { resource: inc/codons.yml }
    - { resource: inc/alphabet.yml }
    - { resource: inc/triplets.yml }
    - { resource: inc/enzymes.yml }
    - { resource: inc/protein.yml }
    - { resource: inc/reductions.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    pk_values:
        EMBOSS:
            N_terminus: 8.6
            K: 10.8
            R: 12.5
            H: 6.5
            C_terminus: 3.6
            D: 3.9
            E: 4.1
            C: 8.5
            Y: 10.1
        DTASelect:
            N_terminus: 8
            K: 10
            R: 12
            H: 6.5
            C_terminus: 3.1
            D: 4.4
            E: 4.4
            C: 8.5
            Y: 10
        Solomon:
            N_terminus: 9.6
            K: 10.5
            R: 125
            H: 6.0
            C_terminus: 2.4
            D: 3.9
            E: 4.3
            C: 8.3
            Y: 10.1
    dna_complements:
        A: T
        T: A
        G: C
        C: G
    rna_complements:
        A: U
        U: A
        G: C
        C: G
    chemical_groups:
        'S': 'H'
        'T': 'H'
        'N': 'M'
        'Q': 'M'
        'C': 'S'
        'M': 'S'
        'P': 'I'
        'D': 'A'
        'E': 'A'
        'K': 'C'
        'R': 'C'
        'H': 'C'
        '*': '*'
        'X': 'X'
    brochures_directory: '%kernel.project_dir%/web/public/uploads/fasta'
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false
