# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{*/Entity,Legacy}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Infra\Controller\:
        resource: '../../src/AppBundle/Infra/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Api\Bioapi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\AminoApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\ElementApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\NucleotidApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\Pam250MatrixDigitApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\PKApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\ProteinReductionApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\TmBaseStackingApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\TripletApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\TripletSpecieApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\TypeIIbEndonucleaseApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\TypeIIEndonucleaseApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\TypeIIsEndonucleaseApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\VendorApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Api\VendorLinkApi:
        arguments:
            - '@csa_guzzle.client.bioapi'
            - '@jms_serializer'

    AppBundle\Domain\Sequence\Builder\SequenceBuilder: ~

    AppBundle\Domain\Database\Interfaces\DatabaseInterface: '@AppBundle\Domain\Database\Service\DatabaseManager'

    AppBundle\Domain\Tools\Interfaces\OligosInterface: '@AppBundle\Domain\Tools\Service\OligosManager'
    AppBundle\Domain\Sequence\Interfaces\ProteinInterface: '@AppBundle\Domain\Sequence\Service\ProteinManager'
    AppBundle\Domain\Sequence\Interfaces\RestrictionEnzymeInterface: '@AppBundle\Domain\Sequence\Service\RestrictionEnzymeManager'
    AppBundle\Domain\Sequence\Interfaces\SequenceAlignmentInterface: '@AppBundle\Domain\Sequence\Service\SequenceAlignmentManager'
    AppBundle\Domain\Sequence\Interfaces\SequenceInterface: '@AppBundle\Domain\Sequence\Service\SequenceBuilder'
    AppBundle\Domain\Sequence\Interfaces\SequenceMatchInterface: '@AppBundle\Domain\Sequence\Service\SequenceMatchManager'

    AppBundle\Api\Interfaces\AminoApiAdapter: '@AppBundle\Api\AminoApi'
    AppBundle\Api\Interfaces\ElementApiAdapter: '@AppBundle\Api\ElementApi'
    AppBundle\Api\Interfaces\NucleotidApiAdapter: '@AppBundle\Api\NucleotidApi'
    AppBundle\Api\Interfaces\Pam250MatrixDigitApiAdapter: '@AppBundle\Api\Pam250MatrixDigitApi'
    AppBundle\Api\Interfaces\ProteinReductionApiAdapter: '@AppBundle\Api\ProteinReductionApi'
    AppBundle\Api\Interfaces\TmBaseStackingApiAdapter: '@AppBundle\Api\TmBaseStackingApi'
    AppBundle\Api\Interfaces\TripletApiAdapter: '@AppBundle\Api\TripletApi'
    AppBundle\Api\Interfaces\TripletSpecieApiAdapter: '@AppBundle\Api\TripletSpecieApi'
    AppBundle\Api\Interfaces\TypeIIbEndonucleaseApiAdapter: '@AppBundle\Api\TypeIIbEndonucleaseApi'
    AppBundle\Api\Interfaces\TypeIIEndonucleaseApiAdapter: '@AppBundle\Api\TypeIIEndonucleaseApi'
    AppBundle\Api\Interfaces\TypeIIsEndonucleaseApiAdapter: '@AppBundle\Api\TypeIIsEndonucleaseApi'
    AppBundle\Api\Interfaces\VendorApiAdapter: '@AppBundle\Api\VendorApi'
    AppBundle\Api\Interfaces\VendorLinkApiAdapter: '@AppBundle\Api\VendorLinkApi'
