# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    limits:
        lowerlimit: 0
        upperlimit: 1
    elements:
        carbone:    12.01
        oxygene:    16.00
        nitrate:    14.01
        hydrogene:  1.01
        phosphore:  30.97
        water:      18.015
    codons:
        Phenylalanine:
            1: 'F'
            3: 'Phe'
        Leucine:
            1: 'L'
            3: 'Leu'
        Isoleucine:
            1: 'I'
            3: 'Ile'
        Methionine:
            1: 'M'
            3: 'Met'
        Valine:
            1: 'V'
            3: 'Val'
        Serine:
            1: 'S'
            3: 'Serine'
        Proline:
            1: 'P'
            3: 'Proline'
        Threonine:
            1: 'T'
            3: 'Thr'
        Alanine:
            1: 'A'
            3: 'Ala'
        Tyrosine:
            1: 'Y'
            3: 'Tyr'
        Histidine:
            1: 'H'
            3: 'His'
        Glutamine:
            1: 'Q'
            3: 'Gin'
        Asparagine:
            1: 'N'
            3: 'Asn'
        Lysine:
            1: 'K'
            3: 'Lys'
        Aspartic_acid:
            1: 'D'
            3: 'Asp'
        Glutamic_acid:
            1: 'E'
            3: 'Glu'
        Cysteine:
            1: 'C'
            3: 'Cys'
        Tryptophan:
            1: 'W'
            3: 'Trp'
        Arginine:
            1: 'R'
            3: 'Arg'
        Glycine:
            1: 'G'
            3: 'Gly'
        STOP:
            1: '*'
            3: 'STP'
    dna_complements:
        A: T
        T: A
        G: C
        C: G
    rna_complements:
        A: U
        U: A
        G: C
        C: G      
    chemical_groups:
        'S': 'H'
        'T': 'H'
        'N': 'M'
        'Q': 'M'
        'C': 'S'
        'M': 'S'
        'P': 'I'
        'D': 'A'
        'E': 'A'
        'K': 'C'
        'R': 'C'
        'H': 'C'
        '*': '*'
        'X': 'X'
    wts:
        A:
            - 89.09
            - 89.09
        B:
            - 132.12
            - 133.1
        C:
            - 121.15
            - 121.15
        D:
            - 133.1
            - 133.1
        E:
            - 147.13
            - 147.13
        F:
            - 165.19
            - 165.19
        G:
            - 75.07
            - 75.07
        H:
            - 155.16
            - 155.16
        I:
            - 131.18
            - 131.18
        K:
            - 146.19
            - 146.19
        L:
            - 131.18
            - 131.18
        M:
            - 149.22
            - 149.22
        N:
            - 132.12
            - 132.12
        P:
            - 115.13
            - 115.13
        Q:
            - 146.15
            - 146.15
        R:
            - 174.21
            - 174.21
        S:
            - 105.09
            - 105.09
        T:
            - 119.12
            - 119.12
        V:
            - 117.15
            - 117.15
        W:
            - 204.22
            - 204.22
        X:
            - 75.07
            - 204.22
        Y:
            - 181.19
            - 181.19
        Z:
            - 146.15
            - 147.13

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: false
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Service\DatabaseManager:
        arguments:
            - '@AppBundle\Service\ParseGenbankManager'
            - '@AppBundle\Service\ParseSwissProtManager'

    AppBundle\Service\ProteinManager:
        arguments: 
            - '@AppBundle\Entity\Protein'
            - %wts%
    
    AppBundle\Service\RestrictionEnzymeManager:
        arguments:
            - '@AppBundle\Entity\RestrictionEnzyme'

    AppBundle\Service\SequenceManager:
        arguments:
            - %dna_complements%
            - %rna_complements%
            - %elements%
            - %chemical_groups%
            - %codons%