parameters:
  limits:
    lowerlimit: 0
    upperlimit: 1
  elements:
    carbone:    12.01
    oxygene:    16.00
    nitrate:    14.01
    hydrogene:  1.01
    phosphore:  30.97
    water:      18.015
  wts:
    A:
      - 89.09
      - 89.09
    B:
      - 132.12
      - 133.1
    C:
      - 121.15
      - 121.15
    D:
      - 133.1
      - 133.1
    E:
      - 147.13
      - 147.13
    F:
      - 165.19
      - 165.19
    G:
      - 75.07
      - 75.07
    H:
      - 155.16
      - 155.16
    I:
      - 131.18
      - 131.18
    K:
      - 146.19
      - 146.19
    L:
      - 131.18
      - 131.18
    M:
      - 149.22
      - 149.22
    N:
      - 132.12
      - 132.12
    P:
      - 115.13
      - 115.13
    Q:
      - 146.15
      - 146.15
    R:
      - 174.21
      - 174.21
    S:
      - 105.09
      - 105.09
    T:
      - 119.12
      - 119.12
    V:
      - 117.15
      - 117.15
    W:
      - 204.22
      - 204.22
    X:
      - 75.07
      - 204.22
    Y:
      - 181.19
      - 181.19
    Z:
      - 146.15
      - 147.13
# From table at http://www.ncbi.nlm.nih.gov/pmc/articles/PMC19045/table/T2/ (SantaLucia, 1998)
  tm_base_stacking:
    enthalpy:
      AA: '-7.9'
      AC: '-8.4'
      AG: '-7.8'
      AT: '-7.2'
      CA: '-8.5'
      CC: '-8.0'
      CG: '-10.6'
      CT: '-7.8'
      GA: '-8.2'
      GC: '-9.8'
      GG: '-8.0'
      GT: '-8.4'
      TA: '-7.2'
      TC: '-8.2'
      TG: '-8.5'
      TT: '-7.9'
    entropy:
      AA: '-22.2'
      AC: '-22.4'
      AG: '-21.0'
      AT: '-20.4'
      CA: '-22.7'
      CC: '-19.9'
      CG: '-27.2'
      CT: '-21.0'
      GA: '-22.2'
      GC: '-24.4'
      GG: '-19.9'
      GT: '-22.4'
      TA: '-21.3'
      TC: '-22.2'
      TG: '-22.7'
      TT: '-22.2'
  dna_weights:
    A_wt: 313.245
    C_wt: 289.215
    G_wt: 329.245
    T_wt: 304.225
  rna_weights:
    A_wt: 329.245
    C_wt: 305.215
    G_wt: 345.245
    U_wt: 306.195
