parameters:
  limits:
    lowerlimit: 0
    upperlimit: 1
  wts:
    A:
      - 89.09
      - 89.09
    B:
      - 132.12
      - 133.1
    C:
      - 121.15
      - 121.15
    D:
      - 133.1
      - 133.1
    E:
      - 147.13
      - 147.13
    F:
      - 165.19
      - 165.19
    G:
      - 75.07
      - 75.07
    H:
      - 155.16
      - 155.16
    I:
      - 131.18
      - 131.18
    K:
      - 146.19
      - 146.19
    L:
      - 131.18
      - 131.18
    M:
      - 149.22
      - 149.22
    N:
      - 132.12
      - 132.12
    P:
      - 115.13
      - 115.13
    Q:
      - 146.15
      - 146.15
    R:
      - 174.21
      - 174.21
    S:
      - 105.09
      - 105.09
    T:
      - 119.12
      - 119.12
    V:
      - 117.15
      - 117.15
    W:
      - 204.22
      - 204.22
    X:
      - 75.07
      - 204.22
    Y:
      - 181.19
      - 181.19
    Z:
      - 146.15
      - 147.13
