parameters:
  vendor_links:
    C:
      name: "Minotech Biotechnology"
      url: "http://www.minotech.gr"
    E:
      name: "Minotech Stratagene"
      url: "http://www.stratagene.com"
    F:
      name: "Fermentas AB"
      url: "http://www.fermentas.com"
    H:
      name: "American Allied Biochemical, Inc."
      url: "http://www.aablabs.com"
    I:
      name: "SibEnzyme Ltd."
      url: "http://www.sibenzyme.com"
    J:
      name: "Nippon Gene Co., Ltd."
      url: "http://www.nippongene.jp"
    K:
      name: "Takara Shuzo Co. Ltd."
      url: "http://www.takarashuzo.co.jp/english/index.htm"
    M:
      name: "Roche Applied Science"
      url: "http://www.roche.com"
    N:
      name: "New England Biolabs"
      url: "http://www.neb.com"
    O:
      name: "Toyobo Biochemicals"
      url: "http://www.toyobo.co.jp/e/"
    P:
      name: "Megabase Research Products"
      url: "http://www.cvienzymes.com"
    Q:
      name: "CHIMERx"
      url: "http://www.CHIMERx.com"
    R:
      name: "Promega Corporation"
      url: "http://www.promega.com"
    S:
      name: "Sigma Chemical Corporation"
      url: "http://www.sigmaaldrich.com"
    U:
      name: "Bangalore Genei"
      url: "http://www.bangaloregenei.com"
    V:
      name: "MRC-Holland"
      url: "http://www.mrc-holland.com"
    X:
      name: "EURx Ltd."
      url: "http://www.eurx.com.pl/index.php?op=catalog&cat=8"
