parameters:
#  pam250_matrix:
#      CC: 12,

#      SC: 0, SS: 2,
#      CS: 0,

#      TC: -2, TS: 1, TT: 3,
#      CT: -2, ST: 1,

#      PC: -3, PS: 1, PT: 0, PP: 6,
#      CP: -3, SP: 1, TP: 0,

#      AC: -2, AS: 1, AT: 1, AP: 1, AA: 2,
#      CA: -2, SA: 1, TA: 1, PA: 1,

#      GC: -3, GS: 1, GT: 0, GP: -1, GA: 1, GG: 5,
#      CG: -3, SG: 1, TG: 0, PG: -1, AG: 1,

#      NC: -4, NS: 1, NT: 0, NP: -1, NA: 0, NG: 0, NN: 2,
#      CN: -4, SN: 1, TN: 0, PN: -1, AN: 0, GN: 0,

#      DC: -5, DS: 0, DT: 0, DP: -1, DA: 0, DG: 1, DN: 2, DD: 4,
#      CD: -5, SD: 0, TD: 0, PD: -1, AD: 0, GD: 1, ND: 2,

#      EC: -5, ES: 0, ET: 0, EP: -1, EA: 0, EG: 0, EN: 1, ED: 3, EE: 4,
#      CE: -5, SE: 0, TE: 0, PE: -1, AE: 0, GE: 0, NE: 1, DE: 3,

#      QC: -5, QS: -1, QT: -1, QP: 0, QA: 0, QG: -1, QN: 1, QD: 2, QE: 2, QQ: 4,
#      CQ: -5, SQ: -1, TQ: -1, PQ: 0, AQ: 0, GQ: -1, NQ: 1, DQ: 2, EQ: 2,

#      HC: -3, HS: -1, HT: -1, HP: 0, HA: -1, HG: -2, HN: 2, HD: 1, HE: 1, HQ: 3, HH: 6,
#      CH: -3, SH: -1, TH: -1, PH: 0, AH: -1, GH: -2, NH: 2, DH: 1, EH: 1, QH: 3,

#      RC: -4, RS: 0, RT: -1, RP: 0, RA: -2, RG: -3, RN: 0, RD: -1, RE: -1, RQ: 1, RH: 2, RR: 6,
#      CR: -4, SR: 0, TR: -1, PR: 0, AR: -2, GR: -3, NR: 0, DR: -1, ER: -1, QR: 1, HR: 2,

#      KC: -5, KS: 0, KT: 0, KP: -1, KA: -1, KG: -2, KN: 1, KD: 0, KE: 0, KQ: 1, KH: 0, KR: 3, KK: 5,
#      CK: -5, SK: 0, TK: 0, PK: -1, AK: -1, GK: -2, NK: 1, DK: 0, EK: 0, QK: 1, HK: 0, RK: 3,

#      MC: -5, MS: -2, MT: -1, MP: -2, MA: -1, MG: -3, MN: -2, MD: -3, ME: -2, MQ: -1, MH: -2, MR: 0, MK: 0, MM: 6,
#      CM: -5, SM: -2, TM: -1, PM: -2, AM: -1, GM: -3, NM: -2, DM: -3, EM: -2, QM: -1, HM: -2, RM: 0, KM: 0,

#      IC: -2, IS: -1, IT: 0, IP: -2, IA: -1, IG: -3, IN: -2, ID: -2, IE: -2, IQ: -2, IH: -2, IR: -2, IK: -2, IM: 2, II: 5,
#      CI: -2, SI: -1, TI: 0, PI: -2, AI: -1, GI: -3, NI: -2, DI: -2, EI: -2, QI: -2, HI: -2, RI: -2, KI: -2, MI: 2,

#      LC: -6, LS: -3, LT: -2, LP: -3, LA: -2, LG: -4, LN: -3, LD: -4, LE: -3, LQ: -2, LH: -2, LR: -3, LK: -3, LM: 4, LI: 2, LL: 6,
#      CL: -6, SL: -3, TL: -2, PL: -3, AL: -2, GL: -4, NL: -3, DL: -4, EL: -3, QL: -2, HL: -2, RL: -3, KL: -3, ML: 4, IL: 2,

#      VC: -2, VS: -1, VT: 0, VP: -1, VA: 0, VG: -1, VN: -2, VD: -2, VE: -2, VQ: -2, VH: -2, VR: -2, VK: -2, VM: 2, VI: 4, VL: 2, VV: 4,
#      CV: -2, SV: -1, TV: 0, PV: -1, AV: 0, GV: -1, NV: -2, DV: -2, EV: -2, QV: -2, HV: -2, RV: -2, KV: -2, MV: 2, IV: 4, LV: 2,

#      FC: -4, FS: -3, FT: -3, FP: -5, FA: -4, FG: -5, FN: -4, FD: -6, FE: -5, FQ: -5, FH: -2, FR: -4, FK: -5, FM: 0, FI: 1, FL: 2, FV: -1, FF: 9,
#      CF: -4, SF: -3, TF: -3, PF: -5, AF: -4, GF: -5, NF: -4, DF: -6, EF: -5, QF: -5, HF: -2, RF: -4, KF: -5, MF: 0, IF: 1, LF: 2, VF: -1,

#      YC: 0, YS: -3, YT: -3, YP: -5, YA: -3, YG: -5, YN: -2, YD: -4, YE: -4, YQ: -4, YH: 0, YR: -4, YK: -4, YM: -2, YI: -1, YL: -1, YV: -2, YF: 7, YY: 10,
#      CY: 0, SY: -3, TY: -3, PY: -5, AY: -3, GY: -5, NY: -2, DY: -4, EY: -4, QY: -4, HY: 0, RY: -4, KY: -4, MY: -2, IY: -1, LY: -1, VY: -2, FY: 7,

#      WC: -8, WS: -2, WT: -5, WP: -6, WA: -6, WG: -7, WN: -4, WD: -7, WE: -7, WQ: -5, WH: 3, WR: 2, WK: -3, WM: -4, WI: -5, WL: -2, WV: -6, WF: 0, WY: 0, WW: 17,
#      CW: -8, SW: -2, TW: -5, PW: -6, AW: -6, GW: -7, NW: -4, DW: -7, EW: -7, QW: -5, HW: 3, RW: 2, KW: -3, MW: -4, IW: -5, LW: -2, VW: -6, FW: 0, YW: 0

  analysis_color:
    polar: 'magenta'
    nonpolar: 'yellow'
    charged: 'red'
    hydrophobic: 'green'
    positively_charged: 'blue'
    negatively_charged: 'red'

  # define generic color
  # the assigment order is the one shown in the list
  # When few colors are needed, the first ones in the list are used
  generic_colors:
    0: "FF0000"
    1: "00FF00"
    2: "0000FF"
    3: "FFFF00"
    4: "FF00FF"
    5: "00FFFF"
    6: "FF8888"
    7: "88FF88"
    8: "8888FF"
    9: "FFFF88"
    10: "FF88FF"
    11: "88FFFF"
    12: "FF3366"
    13: "33FF66"
    14: "3366FF"
    15: "FF6633"
    16: "66FF33"
    17: "6633FF"
    18: "880000"
    19: "008800"

  protein_colors:
    20:
      A: "CCFFFF"
      R: "E60606"
      N: "FF9900"
      D: "FFCC99"
      C: "00FFFF"
      E: "FFCC00"
      Q: "FF6600"
      G: "00FF00"
      H: "FFFF99"
      I: "000088"
      L: "3366FF"
      K: "C64200"
      M: "99CCFF"
      F: "00CCFF"
      P: "FFFF00"
      S: "CCFF99"
      T: "00FF99"
      W: "CC99FF"
      Y: "CCFFCC"
      V: "0000FF"
    2:
      P: "0000FF"
      H: "FF0000"
    5:
      A: "FF0000"
      R: "00FF00"
      C: "0000FF"
      T: "FFFF00"
      D: "00FFFF"
    6:
      A: "FF0000"
      R: "00FF00"
      P: "0000FF"
      N: "8888FF"
      T: "FFFF00"
      D: "00FFFF"
    3IMG:
      P: "E60606"
      N: "FFFF00"
      H: "3366FF"
    5IMG:
      G: "E60606"
      C: "E60606"
      E: "E60606"
      M: "E60606"
      F: "E60606"
    11IMG:
      A: "1B04AE"
      F: "00CCFF"
      C: "CCECFF"
      G: "00FF00"
      S: "89F88B"
      W: "CC99FF"
      Y: "CCFFCC"
      P: "FFFF00"
      D: "FFCC00"
      N: "F4A504"
      H: "EC1504"
    Murphy15:
      L: "FF0000"
      C: "00FF00"
      A: "0000FF"
      G: "FFFF00"
      S: "00FFFF"
      T: "FF00FF"
      P: "880000"
      F: "008800"
      W: "000088"
      E: "888800"
      D: "008888"
      N: "880088"
      Q: "FF8888"
      K: "88FF88"
      H: "8888FF"
    Murphy10:
      L: "FF0000"
      C: "00FF00"
      A: "0000FF"
      G: "FFFF00"
      S: "00FFFF"
      P: "880000"
      F: "008800"
      E: "888800"
      K: "88FF88"
      H: "8888FF"
    Murphy8:
      L: "FF0000"
      A: "0000FF"
      S: "00FFFF"
      P: "880000"
      F: "0000FF"
      E: "008800"
      K: "88FF88"
      H: "0000FF"
    Murphy4:
      L: "00FF00"
      A: "00FFFF"
      F: "FF0000"
      E: "0000FF"
    Murphy2:
      P: "FF0000"
      E: "0000FF"
    Wang5:
      I: "FF0000"
      A: "00FF00"
      G: "FFFF00"
      E: "0000FF"
      K: "00FFFF"
    Wang5v:
      I: "FF0000"
      L: "FFFF00"
      A: "00FF00"
      E: "0000FF"
      K: "00FFFF"
    Wang3:
      I: "FF0000"
      A: "00FF00"
      E: "0000FF"
    Wang2:
      I: "FF0000"
      A: "0000FF"
    Li10:
      C: "FF0000"
      Y: "FFFF00"
      L: "FF00FF"
      V: "FF8888"
      G: "00FFFF"
      P: "88FF88"
      S: "00FF00"
      N: "8888FF"
      E: "0000FF"
      K: "88FFFF"
    Li5:
      Y: "FFFF00"
      I: "FF0000"
      G: "00FFFF"
      S: "00FF00"
      E: "0000FF"
    Li4:
      Y: "FFFF00"
      I: "FF0000"
      S: "00FF00"
      E: "0000FF"
    Li3:
      I: "FF0000"
      S: "00FF00"
      E: "0000FF"

  types_infos:
    20:
      Description: "Complete alphabet"
      Elements: ["-"]
    2:
      Description: "Two letters alphabet"
      Elements:
        AGTSNQDEHRKP: "P: Hydrophilic"
        CMFILVWY: "H: Hydrophobic"
    5:
      Description: "Five letters alphabet: Chemical / structural properties"
      Elements:
        IVL: "A: Aliphatic"
        FYW: "R: Aromatic"
        KRDE: "C: Charged"
        GACS: "T: Tiny"
        TMQNP: "D: Diverse"
    6:
      Description: "Six letters alphabet: Chemical / structural properties #2"
      Elements:
        IVL: "A: Aliphatic"
        FYWH: "R: Aromatic"
        KR: "C: Pos. charged"
        DE: "C: Neg. charged"
        GACS: "T: Tiny"
        TMQNP: "D: Diverse"
    3IMG:
      Description: "3 IMGT amino acid hydropathy alphabet"
      Elements:
        IVLFCMAW: "P: Hydrophilic"
        GTSYPM: "N: Neutral"
        DNEQKR: "H: Hydrophobic"
    5IMG:
      Description: "5 IMGT amino acid volume alphabet"
      Elements:
        GAS: "G: 60-90"
        CDPNT: "C: 108-117"
        EVQH: "E: 138-154"
        MILKR: "M: 162-174"
        FYW: "F: 189-228"
    11IMG:
      Description: "11 IMGT amino acid chemical characteristics alphabet"
      Elements:
        AVIL: "A: Aliphatic"
        F: "F: Phenylalanine"
        CM: "C: Sulfur"
        G: "G: Glycine"
        ST: "S: Hydroxyl"
        W: "W: Tryptophan"
        Y: "Y: Tyrosine"
        P: "P: Proline"
        DE: "A: Acidic"
        NQ: "N: Amide"
        HKR: "H: Basic"
    Murphy15:
      Description: "Murphy et al, 2000; 15 letters alphabet"
      Elements:
        LVIM: "L: Large hydrophobic"
        C: "C"
        A: "A"
        G: "G"
        S: "S"
        T: "T"
        P: "P"
        FY: "F: Hydrophobic/aromatic sidechains"
        W: "W"
        E: "E"
        D: "D"
        N: "N"
        Q: "Q"
        KR: "K: Long-chain positively charged"
        H: "H"
    Murphy10:
      Description: "Murphy et al, 2000; 10 letters alphabet"
      Elements:
        LVIM: "L: Large hydrophobic"
        C: "C"
        A: "A"
        G: "G"
        ST: "S: Polar"
        P: "P"
        FYW: "F:Hydrophobic/aromatic sidechains"
        EDNQ: "E: Charged / polar"
        KR: "K: Long-chain positively charged"
        H: "H"
    Murphy8:
      Description: "Murphy et al, 2000; 8 letters alphabet"
      Elements:
        LVIMC: "L: Hydrophobic"
        AG: "A"
        ST: "S: Polar"
        P: "P"
        FYW: "F: Hydrophobic/aromatic sidechains"
        EDNQ: "E"
        KR: "K: Long-chain positively charged"
        H: "H"
    Murphy4:
      Description: "Murphy et al, 2000; 4 letters alphabet"
      Elements:
        LVIMC: "L: Hydrophobic"
        AGSTP: "A"
        FYW: "F: Hydrophobic/aromatic sidechains"
        EDNQKRH: "E"
    Murphy2:
      Description: "Murphy et al, 2000; 2 letters alphabet"
      Elements:
        LVIMCAGSTPFYW: "P: Hydrophobic"
        EDNQKRH: "E: Hydrophilic"
    Wang5:
      Description: "Wang & Wang, 1999; 5 letters alphabet"
      Elements:
        CMFILVWY: "I"
        ATH: "A"
        GP: "G"
        DE: "E"
        SNQRK: "K"
    Wang5v:
      Description: "Wang & Wang, 1999; 5 letters variant alphabet"
      Elements:
        CMFI: "I"
        LVWY: "L"
        ATGS: "A"
        NQDE: "E"
        HPRK: "K"
    Wang3:
      Description: "Wang & Wang, 1999; 3 letters alphabet"
      Elements:
        CMFILVWY: "I"
        ATHGPR: "A"
        DESNQK: "E"
    Wang2:
      Description: "Wang & Wang, 1999; 2 letters alphabet"
      Elements:
        CMFILVWY: "I"
        ATHGPRDESNQK: "A"
    Li10:
      Description: "Li et al, 2003; 10 letters alphabet"
      Elements:
        C: "C"
        FYW: "Y"
        ML: "L"
        IV: "V"
        G: "G"
        P: "P"
        ATS: "S"
        NH: "N"
        QED: "E"
        RK: "K"
    Li5:
      Description: "Li et al, 2003; 5 letters alphabet"
      Elements:
        CFYW: "Y"
        MLIV: "I"
        G: "G"
        PATS: "S"
        NHQEDRK: "E"
    Li4:
      Description: "Li et al, 2003; 4 letters alphabet"
      Elements:
        CFYW: "Y"
        MLIV: "I"
        GPATS: "S"
        NHQEDRK: "E"
    Li3:
      Description: "Li et al, 2003; 3 letters alphabet"
      Elements:
        CFYWMLIV: "I"
        GPATS: "S"
        NHQEDRK: "E"
