parameters:
  # triplets is the array containing the genetic codes
  triplets_combinations: ["TTT ", "TTC ", "TTA ", "TTG ", "TCT ", "TCC ", "TCA ", "TCG ",
                          "TAT ", "TAC ", "TAA ", "TAG ", "TGT ", "TGC ", "TGA ", "TGG ", "CTT ", "CTC ",
                          "CTA ", "CTG ", "CCT ", "CCC ", "CCA ", "CCG ", "CAT ", "CAC ", "CAA ", "CAG ",
                          "CGT ", "CGC ", "CGA ", "CGG ", "ATT ", "ATC ", "ATA ", "ATG ", "ACT ", "ACC ",
                          "ACA ", "ACG ", "AAT ", "AAC ", "AAA ", "AAG ", "AGT ", "AGC ", "AGA ", "AGG ",
                          "GTT ", "GTC ", "GTA ", "GTG ", "GCT ", "GCC ", "GCA ", "GCG ", "GAT ", "GAC ",
                          "GAA ", "GAG ", "GGT ", "GGC ", "GGA ", "GGG "]

  # Info has been extracted from http://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi?mode
  triplets_list:
    standard_genetic_code: ["TTY","YTN","ATH","ATG","GTN","WSN","CCN","ACN","GCN","TAY","TRR",
                            "CAY","CAR","AAY","AAR","GAY","GAR","TGY","TGG","MGN","GGN","NNN"]
    vertebrate_mitochondrial: ["TTY","YTN","ATY","ATR","GTN","WSN","CCN","ACN","GCN","TAY","WRR",
                               "CAY","CAR","AAY","AAR","GAY","GAR","TGY","TGR","CGN","GGN","NNN"]
    yeast_mitochondrial: ["TTY","TTR","ATY","ATR","GTN","WSN","CCN","MYN","GCN","TAY","TAR","CAY",
                          "CAR","AAY","AAR","GAY","GAR","TGY","TGR","MGN","GGN","NNN"]
    mold_rotozoan_coelenterate_mitochondrial: ["TTY","YTN","ATH","ATG","GTN","WSN","CCN","ACN",
                                               "GCN","TAY","TAR","CAY","CAR","AAY","AAR","GAY",
                                               "GAR","TGY","TGR","MGN","GGN","NNN"]
    invertebrate_mitochondrial: ["TTY","YTN","ATY","ATR","GTN","WSN","CCN","WSN","GCN","TAY","TAR",
                                 "CAY","CAR","AAY","AAR","GAY","GAR","TGY","TGR","CGN","GGN","NNN"]
    ciliate_dasycladacean_hexamita_nuclear: ["TTY","YTN","ATH","ATG","GTN","WSN","CCN","ACN","GCN",
                                             "TAY","TGA","CAY","YAR","AAY","AAR","GAY","GAR","TGY",
                                             "TGG","MGN","GGN","NNN"]
    echinoderm_mitochondrial: ["TTY","YTN","ATH","ATG","GTN","WSN","CCN","WCN","GCN","TAY","TAR",
                               "CAY","CAR","AAH","AAG","GAY","GAR","TGY","TGR","CGN","GGN","NNN"]
    euplotid_nuclear: ["TTY","YTN","ATH","ATG","GTN","WSN","CCN","ACN","GCN","TAY","TAR","CAY","CAR",
                       "AAY","AAR","GAY","GAR","TGH","TGG","MGN","GGN","NNN"]
    bacterial_and_plant_plastid: ["TTY","YTN","ATH","ATG","GTN","WSN","CCN","ACN","GCN","TAY","TRR",
                                  "CAY","CAR","AAY","AAR","GAY","GAR","TGY","TGG","MGN","GGN","NNN"]
    alternative_yeast_nuclear: ["TTY","YTN","ATH","ATG","GTN","HBN","CCN","ACN","GCN","TAY","TRR",
                                "CAY","CAR","AAY","AAR","GAY","GAR","TGY","TGG","MGN","GGN","NNN"]
    ascidian_mitochondrial: ["TTY","YTN","ATY","ATR","GTN","WSN","CCN","ACN","GCN","TAY","TAR","CAY",
                             "CAR","AAY","AAR","GAY","GAR","TGY","TGR","CGN","RGN","NNN"]
    flatworm_mitochondrial: ["TTY","YTN","ATH","ATG","GTN","WSN","CCN","ACN","GCN","TAH","TAG","CAY",
                             "CAR","ATH","AAG","GAY","GAR","TGY","TGR","CGN","GGN","NNN"]
    blepharisma_macronuclear: ["TTY","YTN","ATH","ATG","GTN","WSN","CCN","ACN","GCN","TAY","TRA","CAY",
                               "YAR","AAY","AAR","GAY","GAR","TGY","TGG","MGN","GGN","NNN"]
    chlorophycean_mitochondrial: ["TTY","YWN","ATH","ATG","GTN","WSN","CCN","ACN","GCN","TAY","TRA",
                                  "CAY","CAR","AAY","AAR","GAY","GAR","TGY","TGG","MGN","GGN","NNN"]
    trematode_mitochondrial: ["TTY","YTN","ATY","ATR","GTN","WSN","CCN","ACN","GCN","TAY","TAR","CAY",
                              "CAR","AAH","AAG","GAY","GAR","TGY","TGR","CGN","GGN","NNN"]
    scenedesmus_obliquus_mitochondrial: ["TTY","YWN","ATH","ATG","GTN","WSB","CCN","ACN","GCN","TAY",
                                         "TVR","CAY","CAR","AAY","AAR","GAY","GAR","TGY","TGG","MGN",
                                         "GGN","NNN"]
    thraustochytrium_mitochondrial_code: ["TTY","YTN","ATH","ATG","GTN","WSN","CCN","ACN","GCN","TAY",
                                          "TDR","CAY","CAR","AAY","AAR","GAY","GAR","TGY","TGG","MGN",
                                          "GGN","NNN"]

  # Info has been extracted from http://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi?mode
  triplets:
    standard:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG |TGA )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    vertebrate_mitochondrial:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG |AGA |AGG )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG |TGA )'
      - '(CG. )'
      - '(GG. )'
      - '(\S\S\S )'
    yeast_mitochondrial:
      - '(TTT |TTC )'
      - '(TTA |TTG )'
      - '(ATT |ATC )'
      - '(ATG |ATA )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. |CT. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG |TGA )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    mold_protozoan_coelenterate_mitochondrial:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG |TGA )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    invertebrate_mitochondrial:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC )'
      - '(ATG |ATA )'
      - '(GT. )'
      - '(TC. |AG. )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG |TGA )'
      - '(CG. )'
      - '(GG. )'
      - '(\S\S\S )'
    ciliate_dasycladacean_hexamita_nuclear:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TGA )'
      - '(CAT |CAC )'
      - '(CAA |CAG |TAA |TAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    echinoderm_mitochondrial:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AG. )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAA |AAT |AAC )'
      - '(AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG |TGA )'
      - '(CG. )'
      - '(GG. )'
      - '(\S\S\S )'
    euplotid_nuclear:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC |TGA )'
      - '(TGG )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    bacterial_plant_plastid:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG |TGA )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    alternative_yeast_nuclear:
      - '(TTT |TTC )'
      - '(TTA |TTG |CTA |CTT |CTC )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC |CTG )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG |TGA )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    ascidian_mitochondria:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC )'
      - '(ATG |ATA )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG |TGA )'
      - '(CG. )'
      - '(GG. |AGA |AGG )'
      - '(\S\S\S )'
    flatworm_mitochondrial:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AG. )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC |TAA )'
      - '(TAG )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC |AAA )'
      - '(AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG |TGA )'
      - '(CG. )'
      - '(GG. )'
      - '(\S\S\S )'
    blepharisma_macronuclear:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TGA )'
      - '(CAT |CAC )'
      - '(CAA |CAG |TAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    chlorophycean_mitochondrial:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. |TAG )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TGA )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    trematode_mitochondrial:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. )'
      - '(ATT |ATC )'
      - '(ATG |ATA )'
      - '(GT. )'
      - '(TC. |AG. )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TAG )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC |AAA )'
      - '(AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG |TGA )'
      - '(CG. )'
      - '(GG. )'
      - '(\S\S\S )'
    scenedesmus_obliquus_mitochondrial:
      - '(TTT |TTC )'
      - '(TTA |TTG |CT. |TAG )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TCT |TCC |TCG |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TAA |TGA |TCA )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'
    thraustochytrium_mitochondrial_code:
      - '(TTT |TTC )'
      - '(TTG |CT. )'
      - '(ATT |ATC |ATA )'
      - '(ATG )'
      - '(GT. )'
      - '(TC. |AGT |AGC )'
      - '(CC. )'
      - '(AC. )'
      - '(GC. )'
      - '(TAT |TAC )'
      - '(TTA |TAA |TAG |TGA )'
      - '(CAT |CAC )'
      - '(CAA |CAG )'
      - '(AAT |AAC )'
      - '(AAA |AAG )'
      - '(GAT |GAC )'
      - '(GAA |GAG )'
      - '(TGT |TGC )'
      - '(TGG )'
      - '(CG. |AGA |AGG )'
      - '(GG. )'
      - '(\S\S\S )'