# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Legacy}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Infra\Controller\:
        resource: '../src/Infra/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Domain\Sequence\Builder\SequenceBuilder: ~

    App\Domain\Tools\Interfaces\OligosInterface: '@App\Domain\Tools\Service\OligosManager'
    App\Domain\Sequence\Interfaces\ProteinInterface: '@App\Domain\Sequence\Service\ProteinManager'
    App\Domain\Sequence\Interfaces\RestrictionEnzymeInterface: '@App\Domain\Sequence\Service\RestrictionEnzymeManager'
    App\Domain\Sequence\Interfaces\SequenceAlignmentInterface: '@App\Domain\Sequence\Service\SequenceAlignmentManager'
    App\Domain\Sequence\Interfaces\SequenceInterface: '@App\Domain\Sequence\Service\SequenceBuilder'
    App\Domain\Sequence\Interfaces\SequenceMatchInterface: '@App\Domain\Sequence\Service\SequenceMatchManager'
